{{- if eq .Values.controller "daemonset" }}
apiVersion: {{ template "mcrouter.daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  name: {{ template "mcrouter.fullname" . }}
  labels:
    {{- include "mcrouter.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      {{- include "mcrouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcrouter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "mcrouter.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" | quote }}
        command: ["mcrouter"]
        args:
        - -p {{ .Values.mcrouterCommandParams.port }}
        - --config-file=/etc/mcrouter/config.json
        volumeMounts:
        - name: config
          mountPath: /etc/mcrouter
        ports:
        - name: mcrouter-port
          containerPort: {{ .Values.mcrouterCommandParams.port }}
          hostPort: {{ .Values.daemonset.hostPort }}
        livenessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "mcrouter.fullname" . }}
{{- end -}}