apiVersion: v1
kind: Service
metadata:
  name: {{ template "mcrouter.fullname" . }}
  labels:
    {{- include "mcrouter.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: mcrouter-port
    port: {{ .Values.mcrouterCommandParams.port }}
    targetPort: mcrouter-port
  selector:
    {{- include "mcrouter.selectorLabels" . | nindent 4 }}
